// import type { NextPage } from 'next';
import React from 'react';
// import dynamic from 'next/dynamic';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Styles.module.scss';
import FormCard from "../components/FormCard";
import Wizard from "../components/Wizard.js";
import GridContainer from "../components/Grid/GridContainer.js";
import GridItem from "../components/Grid/GridItem.js";
import { loadStripe } from '@stripe/stripe-js';
import { Elements } from '@stripe/react-stripe-js';

import Step1 from "../components/WizardSteps/Step1.js";
import Step2 from "../components/WizardSteps/Step2.js";
import Step3 from "../components/WizardSteps/Step3.js";
import Step4 from "../components/WizardSteps/Step4.js";
import Step5 from "../components/WizardSteps/Step5.js";


export default function Home() {
  return (
    <div className={`${styles.container} ${styles.bgimage}`}>

      <Head>
        <title>AATC - Conditions Registration</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>   
      <div className='container'>
        <div className='row'>
          {/* <FormCard></FormCard>    */}
          <GridContainer justify="center">
      <GridItem item={true} xs={12} sm={11}>
        <Wizard
          validate
          steps={[
            { stepName: "Welcome", stepComponent: Step1, stepId: "welcome" },
            { stepName: "Registeration", stepComponent: Step2, stepId: "registeration" },
            { stepName: "Type", stepComponent: Step3, stepId: "type" },
            { stepName: "Payment", stepComponent: Step4, stepId: "payment" },
            { stepName: "Thank You", stepComponent: Step5, stepId: "thankyou" },
          ]}
          title="AATC Conditions Registration"
          subtitle="Contractor Community [Shutdowns]"
          finishButtonClick={(e) => console.log(e)}
        />
      </GridItem>
    </GridContainer>
        </div>
      </div>

    </div>
  )
}
